# Generated by Django 5.2.16 on 2026-07-19 05:19

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.CharField(default=gestion.models.nuevo_id_recorrido, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_llegada_programada', models.TimeField(blank=True, null=True)),
                ('distancia_total', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('completado', 'Completado')], default='programado', max_length=20)),
                ('color', models.CharField(default='#6E1E91', max_length=10)),
                ('ruta_coords', models.JSONField(blank=True, default=list)),
                ('punto_inicio', models.CharField(blank=True, max_length=255)),
                ('secretario', models.CharField(blank=True, max_length=150)),
                ('pro_secretario', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['fecha', 'hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='Homenaje',
            fields=[
                ('id', models.CharField(default=gestion.models.nuevo_id_homenaje, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('numero_cuadrilla', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('tiempo_programado', models.IntegerField(default=10)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('cargo_a', models.CharField(choices=[('cuadrilla', 'Cuadrilla'), ('institucion', 'Institución')], default='cuadrilla', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homenajes', to='gestion.recorrido')),
            ],
            options={
                'ordering': ['numero_cuadrilla'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.CharField(default=gestion.models.nuevo_id_evento, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('inicio_cuadrilla', 'Inicio cuadrilla'), ('fin_cuadrilla', 'Fin cuadrilla'), ('inicio_homenaje', 'Inicio homenaje'), ('fin_homenaje', 'Fin homenaje'), ('inicio_cambio', 'Inicio cambio'), ('fin_cambio', 'Fin cambio'), ('inicio_sector', 'Inicio sector'), ('fin_sector', 'Fin sector'), ('observacion', 'Observación')], max_length=20)),
                ('referencia_id', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('sector_numero', models.IntegerField(blank=True, null=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestion.recorrido')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.CharField(default=gestion.models.nuevo_id_cuadrilla, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('cuadrilla', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('honorarios', 'Hermanos Honorarios'), ('invitados', 'Invitados'), ('directorio_general', 'Directorio General'), ('capataces', 'Capataces'), ('dirigentes', 'Dirigentes'), ('adjuntos', 'Adjuntos')], default='regular', max_length=20)),
                ('hermandad_invitada', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('punto_deja', models.CharField(blank=True, max_length=255)),
                ('es_ultima', models.BooleanField(default=False)),
                ('metraje', models.IntegerField(default=0)),
                ('tiempo_estimado', models.IntegerField(default=0)),
                ('hora_toma', models.TimeField(blank=True, null=True)),
                ('hora_deja', models.TimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='gestion.recorrido')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
