# Generated by Django 5.2.16 on 2026-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_seed_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('inicio_cuadrilla', 'Inicio cuadrilla'), ('fin_cuadrilla', 'Fin cuadrilla'), ('inicio_homenaje', 'Inicio homenaje'), ('fin_homenaje', 'Fin homenaje'), ('inicio_cambio', 'Inicio cambio'), ('fin_cambio', 'Fin cambio'), ('inicio_sector', 'Inicio sector'), ('fin_sector', 'Fin sector'), ('pausa_sector', 'Pausa sector'), ('observacion', 'Observación')], max_length=20),
        ),
    ]
